	SUBROUTINE AUDIO(FILE)
		CHARACTER*500 COM2
		CHARACTER*100 COM1
		CHARACTER*14 FIL
		CHARACTER*8 FILE
		CHARACTER*6 DIR
		CHARACTER*10 OS
		LOGICAL SOUND

		COMMON /OS/ OS
		COMMON /SOUND/ SOUND

		IF (.NOT. SOUND) THEN
			RETURN
		END IF

		DIR = 'audio/'

		FIL = ''

		FIL = DIR//FILE

		IF (OS .EQ. 'LINUX') THEN
			COM2 = 'aplay '//FIL

		ELSE IF (OS .EQ. 'WINDOWS') THEN
		COM1 = 'powershell -c "(New-Object Media.SoundPlayer'
		COM2 = COM1 // '''' // FIL // '''' // ').PlaySync()'

		END IF

		CALL SYSTEM(COM2)
	
	END SUBROUTINE AUDIO
	

	SUBROUTINE CHEKOS(VALUE)
		CHARACTER*100 VALUE, COMSPEC, SHELL, VAL
		INTEGER IERR		
		
		VAL = VALUE

		VALUE = ''

		CALL SYSTEM('echo $COMSPEC$', IERR)
			IF (IERR .EQ. 0) THEN
				VALUE = 'WINDOWS'
			ELSE
				VALUE = 'LINUX'
			END IF

	END SUBROUTINE CHEKOS
